import "UnityEngine"
import "UnityEngine.UI"
import "UnityEngine.EventSystems"
import "Slua"
local Declare = require "BSFramework.Core.Global"
require "BSFramework.Core.Version"
require "BSFramework.Core.Class"
require "BSFramework.Log.Log"
require "BSFramework.Manager.SceneManager"
require "BSFramework.Base.GameBaseUI"